-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-12-05 15:43:13 MSK
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE bookings (
    id         NUMBER NOT NULL,
    client_id  NUMBER NOT NULL,
    date_in    DATE NOT NULL,
    date_out   DATE NOT NULL,
    cost       FLOAT NOT NULL,
    staff_id   NUMBER NOT NULL
);

ALTER TABLE bookings ADD CONSTRAINT booking_pk PRIMARY KEY ( id );

CREATE TABLE clients (
    id                 NUMBER NOT NULL,
    first_name         VARCHAR2(400) NOT NULL,
    last_name          VARCHAR2(400) NOT NULL,
    email              VARCHAR2(400) NOT NULL,
    phone              VARCHAR2(400) NOT NULL,
    document_title     VARCHAR2(400) NOT NULL,
    document_file      RAW(2000) NOT NULL,
    document_text      VARCHAR2(400) NOT NULL,
    document_comments  VARCHAR2(400),
    special_requests   VARCHAR2(400)
);

ALTER TABLE clients ADD CONSTRAINT client_pk PRIMARY KEY ( id );

CREATE TABLE houses (
    id           NUMBER NOT NULL,
    name         VARCHAR2(400) NOT NULL,
    price        FLOAT NOT NULL,
    ac           NUMBER NOT NULL,
    tv           NUMBER NOT NULL,
    safe         NUMBER NOT NULL,
    description  VARCHAR2(400),
    type         VARCHAR2(400),
    booking_id   NUMBER
);

ALTER TABLE houses ADD CONSTRAINT house_pk PRIMARY KEY ( id );

CREATE TABLE orders (
    id         NUMBER NOT NULL,
    "date"     DATE NOT NULL,
    client_id  NUMBER NOT NULL,
    cost       FLOAT NOT NULL
);

ALTER TABLE orders ADD CONSTRAINT order_pk PRIMARY KEY ( id );

CREATE TABLE products (
    id     NUMBER NOT NULL,
    title  VARCHAR2(400) NOT NULL,
    price  FLOAT NOT NULL
);

ALTER TABLE products ADD CONSTRAINT product_pk PRIMARY KEY ( id );

CREATE TABLE products_count (
    product_id  NUMBER NOT NULL,
    count       NUMBER NOT NULL,
    order_id    NUMBER NOT NULL
);

ALTER TABLE products_count ADD CONSTRAINT product_count_pk PRIMARY KEY ( product_id,
                                                                         order_id );

CREATE TABLE staffs (
    id          NUMBER NOT NULL,
    first_name  VARCHAR2(400) NOT NULL,
    last_name   VARCHAR2(400) NOT NULL,
    position    VARCHAR2(400) NOT NULL,
    type        VARCHAR2(400) NOT NULL,
    phone       VARCHAR2(400) NOT NULL
);

ALTER TABLE staffs ADD CONSTRAINT staff_pk PRIMARY KEY ( id );

CREATE TABLE staffs_houses (
    house_id  NUMBER NOT NULL,
    staff_id  NUMBER NOT NULL
);

ALTER TABLE staffs_houses ADD CONSTRAINT staff_house_pk PRIMARY KEY ( house_id,
                                                                      staff_id );

ALTER TABLE bookings
    ADD CONSTRAINT booking_client_fk FOREIGN KEY ( client_id )
        REFERENCES clients ( id );

ALTER TABLE bookings
    ADD CONSTRAINT booking_staff_fk FOREIGN KEY ( staff_id )
        REFERENCES staffs ( id );

ALTER TABLE houses
    ADD CONSTRAINT house_booking_fk FOREIGN KEY ( booking_id )
        REFERENCES bookings ( id );

ALTER TABLE orders
    ADD CONSTRAINT order_client_fk FOREIGN KEY ( client_id )
        REFERENCES clients ( id );

ALTER TABLE products_count
    ADD CONSTRAINT product_count_order_fk FOREIGN KEY ( order_id )
        REFERENCES orders ( id );

ALTER TABLE products_count
    ADD CONSTRAINT product_count_product_fk FOREIGN KEY ( product_id )
        REFERENCES products ( id );

ALTER TABLE staffs_houses
    ADD CONSTRAINT staff_house_house_fk FOREIGN KEY ( house_id )
        REFERENCES houses ( id );

ALTER TABLE staffs_houses
    ADD CONSTRAINT staff_house_staff_fk FOREIGN KEY ( staff_id )
        REFERENCES staffs ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
