DROP TABLE STUDENTS;
DROP TABLE PARENTS_INFORMATION;
DROP TABLE STUDENT_ATTENDANCES;
DROP TABLE ACADEMIC_SESSIONS;
DROP TABLE EXAMS_RESULT;
DROP TABLE EXAMS;
DROP TABLE EXAM_TYPES;
DROP TABLE COURSES;
DROP TABLE ONLINE_1;
DROP TABLE SEATED;
DROP TABLE FACULTY_LOGIN_DETAILS;
DROP TABLE FACULTIES;
DROP TABLE DEPARTMENTS;
DROP TABLE STUDENT_COURSE_DETAILS;
DROP TABLE FACULTY_COURSE_DETAILS;


CREATE TABLE PARENTS_INFORMATION (
    id NUMBER,
    par1firstname VARCHAR2(100) NOT NULL,
    par2firstname VARCHAR2(100) NOT NULL,
    par1lastname VARCHAR2(100) NOT NULL,
    par2lastname VARCHAR2(100) NOT NULL,
    CONSTRAINT PARENTS_INFORMATION_pk PRIMARY KEY ( id )
);

CREATE TABLE STUDENTS(
    id NUMBER,
    firstname VARCHAR2(100) NOT NULL,
    lastname  VARCHAR2 (100) NOT NULL,
    regyear TIMESTAMP NOT NULL,
    email VARCHAR2(100) NOT NULL,
    PARENT_id NUMBER NOT NULL,

    CONSTRAINT STUDENTS_pk PRIMARY KEY ( id ),
    CONSTRAINT PARENT_fk FOREIGN KEY (PARENT_id) REFERENCES PARENTS_INFORMATION(id)
);

CREATE TABLE ACADEMIC_SESSIONS(
    id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    CONSTRAINT ACADEMIC_SESSIONS_pk PRIMARY KEY ( id )
);


CREATE TABLE STUDENT_ATTENDANCES (
    number_of_working_days NUMBER NOT NULL,
    number_of_days_off NUMBER NOT NULL,
    eligibity_for_exam NUMBER,
    STUDENT_id NUMBER,
    AS_id NUMBER NOT NULL
);

CREATE TABLE EXAMS_RESULT(
    grade NUMBER NOT NULL

);

CREATE TABLE EXAMS(
    id NUMBER,
    start_date DATE,
    exam_type NUMBER NOT NULL,

    CONSTRAINT EXAM_pk PRIMARY KEY ( id ),

);

CREATE TABLE EXAM_TYPES(
    type NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(100),

    CONSTRAINT EXAM_TYPES_pk PRIMARY KEY ( type ),

);

CREATE TABLE COURSES(
    id NUMBER,
    name VARCHAR2(100) NOT NULL,
    AS_id NUMBER NOT NULL,
    exam_result NUMBER,
    DEPT_id NUMBER,
    LOGON_id NUMBER,
    building VARCHAR2(100),
    room NUMBER,
    date_time VARCHAR2(100),

    CONSTRAINT COURSES_pk PRIMARY KEY ( id ),
);

CREATE TABLE ONLINE_1(
    logon_id NUMBER,
    password VARCHAR2(100) NOT NULL
    CONSTRAINT ONLINE_pk PRIMARY KEY ( logon_id ),
);

CREATE TABLE SEATED(
    building VARCHAR2(100),
    room NUMBER,
    date_time VARCHAR2(100),
    CONSTRAINT SEATED_pk PRIMARY KEY ( building, room, date_time),
);

CREATE TABLE FACULTIES(
    id NUMBER,
    firstname VARCHAR2(100) NOT NULL, 
    lastname VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    salary NUMBER,
    insurance VARCHAR2(100),
    hourlt_rate NUMBER,
    DEPT_id NUMBER

    CONSTRAINT FACULTIES_pk PRIMARY KEY ( id ),

);

CREATE TABLE DEPARTMENTS(
    id NUMBER,
    name VARCHAR2(100) NOT NULL,
    head VARCHAR2(100) NOT NULL,

    CONSTRAINT DEPARTMENTS_pk PRIMARY KEY ( id ),
);

CREATE TABLE STUDENT_COURSE_DETAILS(
    grade NUMBER NOT NULL,
    STUDENT_id NUMBER,
    COURSE_id NUMBER
);

CREATE TABLE FACULTY_COURSE_DETAILS(
    id NUMBER,
    name VARCHAR2(100) NOT NULL,
    head VARCHAR2(100) NOT NULL,
);

CREATE TABLE FACULTY_LOGIN_DETAILS(
    login_data_type VARCHAR2(100),
    faculty_id NUMBER,
    CONSTRAINT FACULTY_LOGIN_DETAILS_pk PRIMARY KEY ( login_data_type ),
);