from .task1 import main as task1
from .task2 import main as task2
from .task3 import main as task3
from .task4 import main as task4
from .task5 import main as task5
from .task6 import main as task6
from .task7 import main as task7
from .task8 import main as task8
from .task9 import main as task9
from .task10 import main as task10
from .task11 import main as task11
from .task12 import main as task12
from .task13 import main as task13
from .task14 import main as task14
from .task15 import main as task15
from .task16 import main as task16
from .task17 import main as task17
from .task18 import main as task18
from .task19 import main as task19
from .task20 import main as task20